### ISSUE TITLE
事件抽取obj任务评价指标一直是0

### ISSUE THREAD

**Issue by yangdonghao621** [taishan1994/PointerNet_Chinese_Information_Extraction#2]
跑了40个epoch的评价指标一直都是0，怎么样才能得到和作者相同的成果呢？
loss一直停在0.1左右
transformers           4.25.1
torch                  1.9.0
```
class EeArgs:
    tasks = ["obj"]
    data_name = "duee"
    data_dir = "ee"
    bert_dir = "model_hub/chinese-bert-wwm-ext/"
    save_dir = "./checkpoints/{}/{}_{}_model.pt".format(data_dir, tasks[0], data_name)
    train_path = "./data/{}/{}/duee_train.json".format(data_dir, data_name)
    dev_path = "./data/{}/{}/duee_dev.json".format(data_dir, data_name)
    test_path = "./data/{}/{}/duee_dev.json".format(data_dir, data_name)
    label_path = "./data/{}/{}/labels.txt".format(data_dir, data_name)
    with open(label_path, "r") as fp:
        entity_label = fp.read().strip().split("\n")
    ent_label2id = {}
    ent_id2label = {}
    for i, label in enumerate(entity_label):
        ent_label2id[label] = i
        ent_id2label[i] = label
    ner_num_labels = len(entity_label)
    train_epoch = 40
    train_batch_size = 32
    eval_batch_size = 32
    eval_step = 500
    max_seq_len = 256
    weight_decay = 0.01
    adam_epsilon = 1e-8
    max_grad_norm = 5.0
    lr = 3e-5
    other_lr = 3e-4
    warmup_proportion = 0.01
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = BertTokenizer.from_pretrained(bert_dir)
```
![image](https://user-images.githubusercontent.com/70182806/209663734-65528c19-d91e-4b15-b2c0-07190fe44ef2.png)

**Comment by yangdonghao621** [comment]
图是20个epoch的截图

**Comment by taishan1994** [comment]
> 跑了40个epoch的评价指标一直都是0，怎么样才能得到和作者相同的成果呢？ loss一直停在0.1左右 transformers 4.25.1 torch 1.9.0
> 
> ```
> class EeArgs:
>     tasks = ["obj"]
>     data_name = "duee"
>     data_dir = "ee"
>     bert_dir = "model_hub/chinese-bert-wwm-ext/"
>     save_dir = "./checkpoints/{}/{}_{}_model.pt".format(data_dir, tasks[0], data_name)
>     train_path = "./data/{}/{}/duee_train.json".format(data_dir, data_name)
>     dev_path = "./data/{}/{}/duee_dev.json".format(data_dir, data_name)
>     test_path = "./data/{}/{}/duee_dev.json".format(data_dir, data_name)
>     label_path = "./data/{}/{}/labels.txt".format(data_dir, data_name)
>     with open(label_path, "r") as fp:
>         entity_label = fp.read().strip().split("\n")
>     ent_label2id = {}
>     ent_id2label = {}
>     for i, label in enumerate(entity_label):
>         ent_label2id[label] = i
>         ent_id2label[i] = label
>     ner_num_labels = len(entity_label)
>     train_epoch = 40
>     train_batch_size = 32
>     eval_batch_size = 32
>     eval_step = 500
>     max_seq_len = 256
>     weight_decay = 0.01
>     adam_epsilon = 1e-8
>     max_grad_norm = 5.0
>     lr = 3e-5
>     other_lr = 3e-4
>     warmup_proportion = 0.01
>     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
>     tokenizer = BertTokenizer.from_pretrained(bert_dir)
> ```
> 
> ![image](https://user-images.githubusercontent.com/70182806/209663734-65528c19-d91e-4b15-b2c0-07190fe44ef2.png)

换成transformers4.5.0试试，在500步进行验证的时候f1应该有0.40左右。

**Comment by yangdonghao621** [comment]
换成transformers4.5.0就可以了，谢谢~

**Comment by wzq1110** [comment]
请问一下，我进行完主体识别之后，我怎么进行客体与关系识别？谢谢~

**Comment by taishan1994** [comment]
> 请问一下，我进行完主体识别之后，我怎么进行客体与关系识别？谢谢~

类型指定为obj，然后按照格式准备好数据集就行。

**Comment by lubaowang** [comment]
所以版本问题导致f1值不一致的根本原因是什么？

**Comment by weizhenzhao** [comment]
大佬，您好，我也遇到了这个问题，torch  1.11.0+cu113 。transformers   4.5.0 .
 评测指标还是一直为0呢。
