### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

### ISSUE THREAD

**Issue by yongxinyou** [taishan1994/PointerNet_Chinese_Information_Extraction#3]
Which version of pythorh and transformers is correct?

**Comment by taishan1994** [comment]
> Which version of pythorh and transformers is correct?

pip install packaging==21.3

**Comment by yongxinyou** [comment]
感谢。但是又出这种bug了。
![image](https://user-images.githubusercontent.com/51067611/220571232-0e1adad9-256c-4a9b-afdf-8587fbcbe1fc.png)
